name: Issue - Stale handler (test)

on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-pr-stale: -1     # skip marking, act on existing stale PRs
          days-before-pr-close: 0      # close PR immediately in this run
          days-before-issue-stale: -1  # skip marking, act on existing stale issues
          days-before-issue-close: 0   # close issue immediately in this run
          exempt-issue-labels: >-
            good first issue,
            priority: P1 must have,
            priority: P2 should have,
            priority: P3 could have
          labels-to-remove-when-unstale: 'status: no issue activity'
          operations-per-run: 100
          stale-issue-label: 'status: no issue activity'
          stale-issue-message: |
            ğŸ‘‹ This test issue is stale.
          close-issue-message: |
            âŒ This test issue is closed.
          stale-pr-label: 'status: no PR activity'
          stale-pr-message: |
            ğŸ‘‹ This test PR is stale.
          close-pr-message: |
            âŒ This test PR is closed.
